package arbol;

import arbol.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jonathan
 */
public class ArbolGrafico extends javax.swing.JFrame implements ActionListener {
    
    Ordenamientos arbolAVL = new Ordenamientos();
        
    //insertando nodos
    int[] arrNodos = {10,5,13,1,6,17,16};
        
        
    
    public ArbolGrafico() {
        initComponents();
        for(int nodo : arrNodos){
        arbolAVL.insertar(nodo);
        }
        BtnInOrden.addActionListener(this);
        BtnPreOrden.addActionListener(this);
        BtnPostOrden.addActionListener(this);
        BtnAgregar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TxtOrdenamiento = new javax.swing.JLabel();
        BtnInOrden = new javax.swing.JButton();
        BtnPreOrden = new javax.swing.JButton();
        BtnPostOrden = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        TxtNuevoNodo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Árbol AVL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel1)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(437, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        TxtOrdenamiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtOrdenamiento.setText("...");

        BtnInOrden.setText("InOrden");

        BtnPreOrden.setText("PreOrden");

        BtnPostOrden.setText("PostOrden");

        BtnAgregar.setText("Agregar Nodo");

        TxtNuevoNodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNuevoNodoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Debe ser un número de máximo 2 dígitos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtOrdenamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BtnAgregar)
                .addGap(26, 26, 26)
                .addComponent(TxtNuevoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(BtnInOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(BtnPreOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BtnPostOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(TxtNuevoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInOrden)
                    .addComponent(BtnPreOrden)
                    .addComponent(BtnPostOrden))
                .addGap(18, 18, 18)
                .addComponent(TxtOrdenamiento)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 900, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNuevoNodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNuevoNodoKeyTyped
        char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c))){
            evt.consume();
        }
        if(TxtNuevoNodo.getText().length() >= 2){
            evt.consume();
        }
    }//GEN-LAST:event_TxtNuevoNodoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolGrafico().setVisible(true);
            }
        });
    }
    
    public int dibujarArbol(Graphics g, Nodos x, int x0, int x1, int y){
         int m = (x0 + x1) / 2;
        g.setColor(Color.BLACK);
        g.fillOval(m, y, 50, 40);
        g.setColor(Color.lightGray);
        g.setFont(new Font("Arial",Font.BOLD,20));
        String t = String.valueOf(x.dato);
        g.drawString(t, m+20, y+30);
        if (x.hijoIzquierdo != null) {
            int x2 = dibujarArbol(g, x.hijoIzquierdo,x0,m,y+50);
            g.drawLine(m+25, y+40, x2+25, y+50);
        }
        if (x.hijoDerecho != null) {
            int x2 = dibujarArbol(g, x.hijoDerecho,m,x1,y+50);
            g.drawLine(m+25, y+40, x2+25, y + 50);
        }
        
        return m;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        dibujarArbol(g, arbolAVL.obtenerRaiz(), 0, this.getWidth()-25, 100);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnInOrden;
    private javax.swing.JButton BtnPostOrden;
    private javax.swing.JButton BtnPreOrden;
    private javax.swing.JTextField TxtNuevoNodo;
    private javax.swing.JLabel TxtOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == BtnInOrden) {
            arbolAVL.inOrden(arbolAVL.obtenerRaiz());
            TxtOrdenamiento.setText("Ordenamiento InOrden: "+arbolAVL.ordenamiento);
            arbolAVL.ordenamiento="";
        }
        if (e.getSource() == BtnPreOrden) {
            arbolAVL.preOrden(arbolAVL.obtenerRaiz());
            TxtOrdenamiento.setText("Ordenamiento PreOrden: "+arbolAVL.ordenamiento);
            arbolAVL.ordenamiento="";
        }
        if (e.getSource() == BtnPostOrden) {
            arbolAVL.postOrden(arbolAVL.obtenerRaiz());
            TxtOrdenamiento.setText("Ordenamiento PostOrden: "+arbolAVL.ordenamiento);
            arbolAVL.ordenamiento="";
        }
        if(e.getSource() == BtnAgregar) {
            int nuevo = Integer.parseInt(TxtNuevoNodo.getText());
            arbolAVL.insertar(nuevo);
            repaint();
            TxtNuevoNodo.setText("");
        }
    }
}
